import {
	BriefcaseIcon,
	CatIcon,
	EnvelopeIcon,
	FlaskIcon,
	GenderMaleIcon,
	GithubLogoIcon,
	NavigationArrowIcon,
	PhoneIcon,
} from '@phosphor-icons/react/ssr';

export const USER: User = {
	firstName: 'Florin',
	lastName: 'Cuzeac',
	username: 'envindavsorg',
	gender: 'homme',
	pronouns: 'il/lui',
	bio: 'Crée, code, innove. Les petits détails comptent.',
	phoneNumber: 'MDYgNTggMDUgODYgNjU=',
	emailAddress: 'Y29udGFjdEBjdXplYWNmbG9yaW4uZnI=',
	sentences: [
		'Imagine, code, crée, inspire.',
		'Chaque petit pixel compte !',
		'Du concept au déploiement !',
		'Chaque petit détail compte !',
	],
	social: {
		github: 'https://github.com/envindavsorg',
		linkedin: 'https://fr.linkedin.com/in/cuzeacflorin',
	},
	overview: [
		{
			id: 'job-title',
			content: 'Développeur Front-End Senior',
			icon: BriefcaseIcon,
			className: 'col-span-full sm:col-span-3',
		},
		{
			id: 'experience-level',
			content: "7 ans d'expérience",
			icon: FlaskIcon,
			className: 'col-span-3',
		},
		{
			id: 'location-city',
			content: 'Paris, France',
			icon: NavigationArrowIcon,
			className: 'col-span-3 lg:col-span-2 lg:row-start-2',
		},
		{
			id: 'github-username',
			content: '@envindavsorg',
			icon: GithubLogoIcon,
			className: 'col-span-3 lg:col-span-2 lg:col-start-3 lg:row-start-2',
		},
		{
			id: 'cat-person',
			content: "J'adore les chats !",
			icon: CatIcon,
			className: 'col-span-3 lg:col-span-2 lg:col-start-5 lg:row-start-2',
		},
		{
			id: 'phone-number',
			content: 'MDYgNTggMDUgODYgNjU=',
			icon: PhoneIcon,
			className: 'col-span-full sm:col-span-3 lg:col-span-2 lg:col-start-1 lg:row-start-3',
		},
		{
			id: 'email-address',
			content: 'Y29udGFjdEBjdXplYWNmbG9yaW4uZnI=',
			icon: EnvelopeIcon,
			className: 'col-span-full sm:col-span-3 lg:col-span-2 lg:col-start-3 lg:row-start-3',
		},
		{
			id: 'pronouns-info',
			content: 'il/lui',
			icon: GenderMaleIcon,
			className: 'col-span-full sm:col-span-3 lg:col-span-2 lg:col-start-5 lg:row-start-3',
		},
	],
	location: {
		city: 'Paris, France',
	},
	website: 'cuzeacflorin.fr',
	jobTitle: 'Développeur et designer web',
	photo: '/images/photo.webp',
	avatar: '/images/avatar.webp',
	ogImage: '/images/og-image-dark.png?t=1755355653',
	namePronunciationUrl: '/audio/florin.mp3',
	documents: {
		cv: {
			content: `
Découvrez mon parcours professionnel à travers mon CV détaillé, qui retrace mes expériences,
compétences techniques et réalisations dans le développement web full-stack.
Vous y trouverez un aperçu complet de mon expertise et de ma progression dans le domaine.

Pour recevoir une copie actualisée directement dans votre boîte e-mail, cliquez sur le bouton ci-dessous.
Je serai ravi d'échanger avec vous sur d'éventuelles opportunités de collaboration.
`,
			url: 'https://cfhi75vpdo.ufs.sh/f/tIhJKzZYPGQBq3bQllCjGzmQByFvYMdbDwUilx4TH8AX3eZ5',
			name: 'cv_florin_cuzeac.pdf',
			title: 'Voir ou télécharger mon CV',
		},
	},
	jobs: [
		{
			title: 'Développeur Front-End Senior',
			company: 'WeFix by Fnac',
			website: 'https://wefix.net',
		},
	],
	keywords: [
		'florin',
		'cuzeac',
		'cuzeac florin',
		'florin cuzeac',
		'envindavsorg',
		'dev',
		'developer',
		'web developer',
		'web designer',
		'front-end developer',
		'front-end designer',
		'freelance',
		'freelance developer',
		'freelance web developer',
		'freelance web designer',
		'freelance front-end developer',
		'freelance front-end designer',
		'paris',
		'france',
		'html',
		'css',
		'sass',
		'javascript',
		'typescript',
		'react',
		'nextjs',
		'tailwindcss',
		'nodejs',
		'npm',
		'pnpm',
		'postgresql',
		'pug',
		'vue',
		'git',
		'bun',
		'express',
		'fastify',
		'markdown',
		'mongodb',
	],
	dateCreated: '2025-09-01',
};
